// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: proto/sql_mapper.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SQLMapperService_MapSQLShot_FullMethodName = "/rpc.SQLMapperService/MapSQLShot"
)

// SQLMapperServiceClient is the client API for SQLMapperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SQLMapperServiceClient interface {
	MapSQLShot(ctx context.Context, in *MapSQLShotRequest, opts ...grpc.CallOption) (*MapSQLShotResponse, error)
}

type sQLMapperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSQLMapperServiceClient(cc grpc.ClientConnInterface) SQLMapperServiceClient {
	return &sQLMapperServiceClient{cc}
}

func (c *sQLMapperServiceClient) MapSQLShot(ctx context.Context, in *MapSQLShotRequest, opts ...grpc.CallOption) (*MapSQLShotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapSQLShotResponse)
	err := c.cc.Invoke(ctx, SQLMapperService_MapSQLShot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SQLMapperServiceServer is the server API for SQLMapperService service.
// All implementations must embed UnimplementedSQLMapperServiceServer
// for forward compatibility.
type SQLMapperServiceServer interface {
	MapSQLShot(context.Context, *MapSQLShotRequest) (*MapSQLShotResponse, error)
	mustEmbedUnimplementedSQLMapperServiceServer()
}

// UnimplementedSQLMapperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSQLMapperServiceServer struct{}

func (UnimplementedSQLMapperServiceServer) MapSQLShot(context.Context, *MapSQLShotRequest) (*MapSQLShotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MapSQLShot not implemented")
}
func (UnimplementedSQLMapperServiceServer) mustEmbedUnimplementedSQLMapperServiceServer() {}
func (UnimplementedSQLMapperServiceServer) testEmbeddedByValue()                          {}

// UnsafeSQLMapperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SQLMapperServiceServer will
// result in compilation errors.
type UnsafeSQLMapperServiceServer interface {
	mustEmbedUnimplementedSQLMapperServiceServer()
}

func RegisterSQLMapperServiceServer(s grpc.ServiceRegistrar, srv SQLMapperServiceServer) {
	// If the following call panics, it indicates UnimplementedSQLMapperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SQLMapperService_ServiceDesc, srv)
}

func _SQLMapperService_MapSQLShot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapSQLShotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SQLMapperServiceServer).MapSQLShot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SQLMapperService_MapSQLShot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SQLMapperServiceServer).MapSQLShot(ctx, req.(*MapSQLShotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SQLMapperService_ServiceDesc is the grpc.ServiceDesc for SQLMapperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SQLMapperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.SQLMapperService",
	HandlerType: (*SQLMapperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MapSQLShot",
			Handler:    _SQLMapperService_MapSQLShot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sql_mapper.proto",
}
