// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/sql_mapper.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapSQLShotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Dbname        string                 `protobuf:"bytes,3,opt,name=dbname,proto3" json:"dbname,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Table         string                 `protobuf:"bytes,6,opt,name=table,proto3" json:"table,omitempty"`
	PayloadCol    string                 `protobuf:"bytes,7,opt,name=payload_col,json=payloadCol,proto3" json:"payload_col,omitempty"`
	Topic         string                 `protobuf:"bytes,8,opt,name=topic,proto3" json:"topic,omitempty"`
	Sql           string                 `protobuf:"bytes,9,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapSQLShotRequest) Reset() {
	*x = MapSQLShotRequest{}
	mi := &file_proto_sql_mapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapSQLShotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapSQLShotRequest) ProtoMessage() {}

func (x *MapSQLShotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sql_mapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapSQLShotRequest.ProtoReflect.Descriptor instead.
func (*MapSQLShotRequest) Descriptor() ([]byte, []int) {
	return file_proto_sql_mapper_proto_rawDescGZIP(), []int{0}
}

func (x *MapSQLShotRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *MapSQLShotRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MapSQLShotRequest) GetDbname() string {
	if x != nil {
		return x.Dbname
	}
	return ""
}

func (x *MapSQLShotRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MapSQLShotRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MapSQLShotRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *MapSQLShotRequest) GetPayloadCol() string {
	if x != nil {
		return x.PayloadCol
	}
	return ""
}

func (x *MapSQLShotRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MapSQLShotRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type MapSQLShotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MappedSql     string                 `protobuf:"bytes,1,opt,name=mapped_sql,json=mappedSql,proto3" json:"mapped_sql,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapSQLShotResponse) Reset() {
	*x = MapSQLShotResponse{}
	mi := &file_proto_sql_mapper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapSQLShotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapSQLShotResponse) ProtoMessage() {}

func (x *MapSQLShotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sql_mapper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapSQLShotResponse.ProtoReflect.Descriptor instead.
func (*MapSQLShotResponse) Descriptor() ([]byte, []int) {
	return file_proto_sql_mapper_proto_rawDescGZIP(), []int{1}
}

func (x *MapSQLShotResponse) GetMappedSql() string {
	if x != nil {
		return x.MappedSql
	}
	return ""
}

func (x *MapSQLShotResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_sql_mapper_proto protoreflect.FileDescriptor

const file_proto_sql_mapper_proto_rawDesc = "" +
	"\n" +
	"\x16proto/sql_mapper.proto\x12\x03rpc\"\xea\x01\n" +
	"\x11MapSQLShotRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x16\n" +
	"\x06dbname\x18\x03 \x01(\tR\x06dbname\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x14\n" +
	"\x05table\x18\x06 \x01(\tR\x05table\x12\x1f\n" +
	"\vpayload_col\x18\a \x01(\tR\n" +
	"payloadCol\x12\x14\n" +
	"\x05topic\x18\b \x01(\tR\x05topic\x12\x10\n" +
	"\x03sql\x18\t \x01(\tR\x03sql\"I\n" +
	"\x12MapSQLShotResponse\x12\x1d\n" +
	"\n" +
	"mapped_sql\x18\x01 \x01(\tR\tmappedSql\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2Q\n" +
	"\x10SQLMapperService\x12=\n" +
	"\n" +
	"MapSQLShot\x12\x16.rpc.MapSQLShotRequest\x1a\x17.rpc.MapSQLShotResponseB\x10Z\x0esqlalchemy/rpcb\x06proto3"

var (
	file_proto_sql_mapper_proto_rawDescOnce sync.Once
	file_proto_sql_mapper_proto_rawDescData []byte
)

func file_proto_sql_mapper_proto_rawDescGZIP() []byte {
	file_proto_sql_mapper_proto_rawDescOnce.Do(func() {
		file_proto_sql_mapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sql_mapper_proto_rawDesc), len(file_proto_sql_mapper_proto_rawDesc)))
	})
	return file_proto_sql_mapper_proto_rawDescData
}

var file_proto_sql_mapper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sql_mapper_proto_goTypes = []any{
	(*MapSQLShotRequest)(nil),  // 0: rpc.MapSQLShotRequest
	(*MapSQLShotResponse)(nil), // 1: rpc.MapSQLShotResponse
}
var file_proto_sql_mapper_proto_depIdxs = []int32{
	0, // 0: rpc.SQLMapperService.MapSQLShot:input_type -> rpc.MapSQLShotRequest
	1, // 1: rpc.SQLMapperService.MapSQLShot:output_type -> rpc.MapSQLShotResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sql_mapper_proto_init() }
func file_proto_sql_mapper_proto_init() {
	if File_proto_sql_mapper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sql_mapper_proto_rawDesc), len(file_proto_sql_mapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sql_mapper_proto_goTypes,
		DependencyIndexes: file_proto_sql_mapper_proto_depIdxs,
		MessageInfos:      file_proto_sql_mapper_proto_msgTypes,
	}.Build()
	File_proto_sql_mapper_proto = out.File
	file_proto_sql_mapper_proto_goTypes = nil
	file_proto_sql_mapper_proto_depIdxs = nil
}
